#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
# python manage.py build_solr_schema --configure-directory /solr

if [ "$PRODUCTION" = "true" ]; then
	python manage.py collectstatic --no-input
	# python manage.py rebuild_index --noinput &
fi

# execute the provided command (from the 'command' property in Docker Compose)
exec "$@"
